# Here you can change the language of this module.
# Currently, the following languages are available:
#
#  'en' -> English translations.
#  'de' -> German translations.
module-language: en
# Here you can enable and disable individual modules. Please note that any changes will require a server restart.
default-currency:
  # Start Balance if the player comes new to the server.
  start-balance: 200.00
  # Printing a first join message to the new Player in Chat.
  enable-first-join-message: true
  # currency via plural
  currency-name-plural: 'EURs'
  # currency via singular
  currency-name-singular: 'EUR'
  fractional-digits: 2
  # The max possible money amount. If a player reaches this value, he can't get any more money.
  # LightEconomy can process a maximum of:
  # - 999,999,999,999,999,999,999,999,999,999,999,999,999,999,999,999,999,99.
  # This is the maximum number you can use.
  max-pocket-balance: 999,999,999,999,999,999,999,999,999,999,999,999,999,999,999,999,999,99
main-settings:
  date-format: 'dd:MM:yyyy'