name: lightEconomy
author: lightPlugins
version: 0.1.0
main: io.lightplugins.economy.LightEconomy
api-version: 1.17
depend: [light]
softdepend: []
loadbefore: [Essentials, Towny]
libraries: []
#  - org.mariadb.jdbc:mariadb-java-client:2.7.4
#  - com.zaxxer:HikariCP:5.1.0
commands:
  lighteconomy:
    description: The root command for lightEconomy overall
    aliases: [lighteco, le, economy]
  eco:
    description: The root command for module [eco]
    aliases: [money, balance, bal, lighteco]
  bank:
    description: The root command for module [bank]
    aliases: [b, bk, lightbank]